"""
Output generation step.

Generates 24-hour threshold arrays and preview data for frontend.
"""

from datetime import datetime, timedelta
from typing import Any

import numpy as np
import pandas as pd

from smart_threshold.algorithms import AlgorithmResult


def parse_step_to_minutes(step: str) -> int:
    """
    Convert step string to minutes.

    Args:
        step: Step string like "1m", "5m", "15m", "1h"

    Returns:
        Number of minutes
    """
    step_map = {
        "1m": 1,
        "5m": 5,
        "15m": 15,
        "30m": 30,
        "1h": 60,
        "1d": 1440,
    }
    return step_map.get(step, 1)


def generate_output(
    prediction: AlgorithmResult,
    train_data_stats: dict[str, float],
    validation_metrics: dict[str, Any],
    train_data: pd.Series = None,
    train_end: datetime = None,
    step: str = "1m",
) -> dict[str, Any]:
    """
    Generate output data for storage and visualization.

    Args:
        prediction: Algorithm prediction result
        train_data_stats: Statistics from training data
        validation_metrics: Validation metrics
        train_data: Original training data (optional, for preview)
        train_end: Training end timestamp (optional, for fallback timestamp generation)
        step: Data sampling interval (e.g., "1m", "5m")

    Returns:
        Output dictionary with threshold arrays and preview data
    """
    # Generate threshold arrays from prediction
    upper_bounds = prediction.yhat_upper.tolist()
    lower_bounds = prediction.yhat_lower.tolist()
    yhat = prediction.yhat.tolist()

    # Use actual prediction length
    target_length = len(yhat)

    # Use timestamps from prediction result directly (generated by algorithm)
    # This ensures timestamps are continuous with training data
    if prediction.timestamps and len(prediction.timestamps) > 0:
        timestamps = [ts.strftime("%Y-%m-%d %H:%M:%S") for ts in prediction.timestamps]
    else:
        # Fallback: generate timestamps from train_end if algorithm didn't provide them
        step_minutes = parse_step_to_minutes(step)
        start_time = train_end or datetime.now()
        timestamps = [
            (start_time + timedelta(minutes=i * step_minutes)).strftime("%Y-%m-%d %H:%M:%S")
            for i in range(target_length)
        ]

    # Create preview data for ECharts (show all prediction data for full visualization)
    preview_data = {
        "timestamps": timestamps,
        "predicted": yhat,
        "upper": upper_bounds,
        "lower": lower_bounds,
    }

    # Add original training data to preview (show all training data for full context)
    if train_data is not None and len(train_data) > 0:
        preview_train_points = len(train_data)
        train_timestamps = [
            ts.strftime("%Y-%m-%d %H:%M:%S")
            for ts in train_data.index[-preview_train_points:]
        ]
        train_values = train_data.values[-preview_train_points:].tolist()

        preview_data["train_timestamps"] = train_timestamps
        preview_data["train_values"] = train_values

        # Add metadata for continuity checking
        preview_data["train_last_timestamp"] = train_data.index[-1].strftime("%Y-%m-%d %H:%M:%S")
        preview_data["predict_first_timestamp"] = timestamps[0] if timestamps else None

        # Calculate gap between train end and predict start (in minutes)
        if timestamps:
            train_last = train_data.index[-1]
            predict_first = prediction.timestamps[0] if prediction.timestamps else None
            if predict_first:
                gap_minutes = (predict_first - train_last).total_seconds() / 60
                preview_data["gap_minutes"] = gap_minutes

    # Build output
    output = {
        "upper_bounds": upper_bounds,
        "lower_bounds": lower_bounds,
        "predicted": yhat,
        "preview_data": preview_data,
        "metadata": {
            "algorithm": prediction.metadata.get("algorithm", "unknown"),
            "generated_at": datetime.now().isoformat(),
            "train_data_stats": train_data_stats,
            "validation_metrics": validation_metrics,
            "prediction_metadata": prediction.metadata,
        }
    }

    return output


def format_for_echarts(
    timestamps: list[datetime],
    actual_values: list[float] | None,
    predicted: np.ndarray,
    upper: np.ndarray,
    lower: np.ndarray,
) -> dict[str, Any]:
    """
    Format data for ECharts visualization.

    Args:
        timestamps: Timestamps
        actual_values: Actual data values (optional)
        predicted: Predicted values
        upper: Upper bounds
        lower: Lower bounds

    Returns:
        ECharts-compatible data structure
    """
    ts_str = [ts.strftime("%Y-%m-%d %H:%M:%S") for ts in timestamps]

    result = {
        "xAxis": {"type": "category", "data": ts_str},
        "series": [
            {
                "name": "Predicted",
                "type": "line",
                "data": predicted.tolist(),
                "lineStyle": {"color": "#5470c6"},
            },
            {
                "name": "Upper Bound",
                "type": "line",
                "data": upper.tolist(),
                "lineStyle": {"color": "#91cc75", "type": "dashed"},
                "itemStyle": {"opacity": 0.5},
            },
            {
                "name": "Lower Bound",
                "type": "line",
                "data": lower.tolist(),
                "lineStyle": {"color": "#91cc75", "type": "dashed"},
                "itemStyle": {"opacity": 0.5},
            },
        ],
    }

    if actual_values is not None:
        result["series"].insert(0, {
            "name": "Actual",
            "type": "line",
            "data": actual_values,
            "lineStyle": {"color": "#ee6666"},
        })

    return result